config/routes.rb
FrontGuy::Engine.routes.draw do
  resources :categories do
    resources :components
  end

  resources :components do
    resources :examples
  end



  root to: 'components#index'
  get '/:id' => 'components#index'
end

app/controllers/front_guy/categories_controller.rb
module FrontGuy
  class CategoriesController < ApplicationController

    def new
      @category = FrontGuy::Category.new
    end

    def edit
      @category = FrontGuy::Category.find(params[:id])
    end

    def create
      @category = FrontGuy::Category.new(params)
      @category.save
      redirect_to category_components_path(@category)
    end
  end
end

app/controllers/front_guy/components_controller.rb
module FrontGuy
  class ComponentsController < ApplicationController

    layout 'front_guy'

    def index
      @categories = FrontGuy::Category.all
      @category = FrontGuy::Category.current_or_primary(params)
      return unless @category
      @components = @category.components
    end

    def new
      @component = FrontGuy::Component.new(params)
    end

    def edit
      @component = FrontGuy::Component.find(params[:id])
    end

    def create
      @component = FrontGuy::Component.new(params)
      @component.save
      redirect_to category_components_path(@component.category_id, uid: @component.uid)
    end
  end
end

app/controllers/front_guy/examples_controller.rb
module FrontGuy
  class ExamplesController < ApplicationController
    def create
      @example = FrontGuy::Example.new(params)
      @example.save
      redirect_to components_path
    end

    def new
      @example = FrontGuy::Example.new(params)
    end

    def edit
      @example = FrontGuy::Example.find(params[:id])
    end

    def create
      @example = FrontGuy::Example.new(params)
      @example.save
      redirect_to category_components_path(@example.component.category_id)
    end
  end
end

app/views/front_guy/categories/_form.haml
= form_tag categories_path(uid: @category) do
  %fieldset
    %legend Add category
    %label{ for: 'title' }
      title
    = text_field_tag :title, @category.title, required: true
    = submit_tag 'Create'

app/views/front_guy/categories/edit.haml
= render 'form'

app/views/front_guy/categories/new.haml
= render 'form'

app/views/front_guy/components/_form.haml
= form_tag category_components_path(@component.category_id, uid: @component), method: :create do
  %fieldset
    %legend New coponents
    %label_tag{ for: 'title'}
      title
    = text_field_tag :title, @component.title,  required: true
    = submit_tag 'Create'

app/views/front_guy/components/edit.haml
= render 'form'

app/views/front_guy/components/index.haml
= link_to 'Front Guy', components_path

%ul
  - @categories.each do |category|
    %li= link_to category.title, category_components_path(category)
  %li= link_to '+ category', new_category_path

- if @category
  %h1.text
    = @category.title
    %small
      = link_to 'edit', edit_category_path(@category)
  = link_to '+ component', new_category_component_path(@category)

  - @components.each do |component|
    %h4
      = component.title
      %small= link_to 'edit', edit_category_component_path(@category, component)
    = link_to '+ example', new_component_example_path(component)
    %br
    - component.examples.each do |example|
      %h6
        = example.title
        %small= link_to 'edit', edit_component_example_path(component, example)
      %p
        = example.description

      %div
        %div
          - if example.language == 'haml'
            :ruby
              raw_preview = begin
                              Haml::Engine.new(example.body).render
                            rescue
                              'Something went wrong...'
                            end
            = raw(raw_preview)
          - else
            = raw(example.body)

        %pre
          %code{ 'data-lang' => example.language, class: example.language }
            = preserve do
              = example.body

    %hr
- else
  Create your first category

app/views/front_guy/components/new.haml
= render 'form'

app/views/front_guy/examples/_form.haml
// show in right sidebar list of existing components
= form_tag component_examples_path(@example.component_id, uid: @example),
  class: '', style: '', method: :post do
  .language
    %label{ for: 'language' }
      Language
    = select_tag :language, options_for_select(%w(haml html), @example.language), required: true
  .title
    %label{ for: 'title' }
      Title
    = text_field_tag :title, @example.title
  .description
    %label{ for: 'description' }
      Description
    = text_area_tag :description, @example.description
  .body
    %label{ for: 'body' }
      Code
    = text_area_tag :body, @example.body, required: true
  .controls
    = submit_tag 'Save'

app/views/front_guy/examples/edit.html.haml
= render 'form'

app/views/front_guy/examples/new.haml
= render 'form'

app/views/front_guy/layouts/front_guy.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Dummy
    = stylesheet_link_tag    'front_guy/application', media: 'all'
    = csrf_meta_tags
  %body
    = yield